df <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
globalActivePower <- as.numeric(df$Global_active_power)
png("plot1.png", width=480, height=480)
hist(globalActivePower, col = "red", main ="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()